// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7o4FV0tQqzPg2tJNP_m-VHvmzyg9L21g',
    appId: '1:896182717961:web:07c14471dd446fc225b2d8',
    messagingSenderId: '896182717961',
    projectId: 'e-commerce-9596e',
    authDomain: 'e-commerce-9596e.firebaseapp.com',
    storageBucket: 'e-commerce-9596e.firebasestorage.app',
    measurementId: 'G-BWDX0PDD7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfXElddhmH39KnD8HecP1uQQGftLv6RYs',
    appId: '1:896182717961:android:49f6ae5d1316f8b625b2d8',
    messagingSenderId: '896182717961',
    projectId: 'e-commerce-9596e',
    storageBucket: 'e-commerce-9596e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoQQxcTfYfv3YgGw0TYKDHPqyFjDYbR8',
    appId: '1:896182717961:ios:6d2f9b7931a506f625b2d8',
    messagingSenderId: '896182717961',
    projectId: 'e-commerce-9596e',
    storageBucket: 'e-commerce-9596e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFoQQxcTfYfv3YgGw0TYKDHPqyFjDYbR8',
    appId: '1:896182717961:ios:6d2f9b7931a506f625b2d8',
    messagingSenderId: '896182717961',
    projectId: 'e-commerce-9596e',
    storageBucket: 'e-commerce-9596e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7o4FV0tQqzPg2tJNP_m-VHvmzyg9L21g',
    appId: '1:896182717961:web:d522649c79410d7c25b2d8',
    messagingSenderId: '896182717961',
    projectId: 'e-commerce-9596e',
    authDomain: 'e-commerce-9596e.firebaseapp.com',
    storageBucket: 'e-commerce-9596e.firebasestorage.app',
    measurementId: 'G-M0XNKT4BPL',
  );
}
